spring.application.name=super-inter-backend

# Carga variables locales desde .env (si existe). El archivo no se versiona.
spring.config.import=optional:file:.env[.properties]

# Conexión a PostgreSQL mediante JDBC
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}